### PR TITLE
Add support for channel

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This adds a 'channels' keyword to the parser. When declaring channel, for each channel one can declare the active ids ('ids') (which can be altered in the resource), whether or not the channel can be selected from within a command ('can_select') (ie Ch 1:VOLT:IMM is supported).
If a device property can be used to select a channel it should be declared under the name 'select_channel'.
This also adds support for concatenating multiple commands separated by a special character (';' by default and can be specified by declaring a 'delimiter' field.
I also re-factored some things I needed in channel away from devices, they are now in component.py

I added some very basic tests also.

This is ready for review from my point of view. I will try to prepare another PR for sending error messages to an error queue and declare a dialog to query the last error.

### CODE REVIEW

**Comment by hgrecco** [comment]
Can you rebase to the current master? I will merge it right away.

**Comment by hgrecco** [comment]
Thanks!

**Comment by MatthieuDartiailh** [comment]
Done. I also rebased the error queue PR.

**Comment by MatthieuDartiailh** [comment]
I will fix the python 3 issue this afternoon.

**Comment by hgrecco** [comment]
Great! I have merge this.

**Pull request merged**
