### PR TITLE
Resolves issue #15

### PR DESCRIPTION
**Pull request by famish99**
* If no response is provided for setter/getter then do not push anything onto the output buffer.
* Also if a read is performed on an empty buffer, return an error.

### CODE REVIEW

**Comment by famish99** [comment]
If you think the error handling is a bit off, I'm working on more sophisticated error handling which I can submit a pull request for later.

**Comment by hgrecco** [comment]
I think it looks good. It would be great if you could provide some tests the new code and then I will merge it. Right now I am doing a lazy but effective way. The test suite just goes over the device provided in default and call all commands (which basically test almost all features of pyvisa-sim). You can do the same by providing a SCPI like device in default. 

For errors, leave that for another Pull Request and please also look at #13 which I think is in the line what you are needing.

**Comment by famish99** [comment]
Ok, I've been unittests on my own end as well so I'll check them in with the next commit.

**Comment by hgrecco** [comment]
I think now this is kind of messy. Please do the following. 
- Add another PR with **only** the empty response part and its tests. I will merge that first.
- Put the error part in another pull request. We will need to discuss this. I am not happy with adding all the VISA errors the way you did. But let's leave this discussion for another issue.

**Comment by famish99** [comment]
Sorry about that. I'm still a bit green to git, I didn't realize when I made the subsequent commits that the pull request would follow the HEAD. I'll try to close this one and reopen it with just the empty response.

As for the error handling, I'm not happy with seeding the eval dictionary the way I did either, but it was more of a security concern, we can definitely make it cleaner if it was wider open. But I really did need a way to raise exceptions to test my code properly.

**Comment by hgrecco** [comment]
No problem at all! Let's look at the implementation together to find the most optimal way.

**Comment by hgrecco** [comment]
Looking at your code, I think that you are confused about the boundaries of PyVISA-sim. Just like a real device knows nothing about PyVISA, a simulated device should operate in the same way. For example, a timeout is raised when the device does not answer in time. So the only thing that the device should know about is not to answer.

**Comment by famish99** [comment]
I could try to pull out the exception code and leave in the error registers.

**Comment by hgrecco** [comment]
Exactly. I think it goes in that lines. With your other PR, if there is no response, you already get an TimeOut if you do a query.

**Comment by famish99** [comment]
You actually get an index error which would be something I'll need to sort
out.

**Comment by hgrecco** [comment]
Yes. But the way to do it by doing what any instrument will do. When you try to read and there is nothing in the buffer you should wait until something appears within certain time. With this in mind:
1.- If there is something in the output buffer, `Device.read` should return the first byt.
2.- If there is nothing in the output buffer, `Device.read` should raise an error (it used to be `queue.Empty` because the output buffer used to be a `Queue`. We then refactored the buffer but not the error).
3.- If **2**, the error is captured inside the `read` of any session which does the wating and retrying to simulate a time out. This exactly how it is done. See for example. gpib.py line 44 and the same in serial, tcpip and usb.
4.- Remove anything about the error from `Device.read`. `Device.read` should **not** write to the output buffer. Only take things out from it.

**Comment by famish99** [comment]
Ok, I think the latest commit should reflect what you've listed.

**Comment by hgrecco** [comment]
Can you rebase your repo to mine, then close all the Pull Requests and redo them because it is kind of messy. It might also be a good idea if you can squash your commits into three or four.

**Pull request closed without merging**
