### PR TITLE
Fix python 3 compatibilities issues.

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by hgrecco** [comment]
Thanks! By the way, I think we are in good shape to release 0.2. We can do another release when the error queue is ready, ok?

**Comment by MatthieuDartiailh** [comment]
As you wish. I might find some time today to finish the error queues (I just need to add some tests and check Python 3)

**Comment by hgrecco** [comment]
I can wait till the end of the week. Thanks!

**Comment by hgrecco** [comment]
Thanks!

**Pull request merged**
