### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by famish99**
Fixed unexpected read timeout behavior. Fixed loading of config files that aren't the default config.

### CODE REVIEW

**Comment by hgrecco** [comment]
Can you provide some arguments for this commit. I think the current behavior is the correct one. If nothing is read, it should try the loop again (`continue`) without going through the whole loop.

**Comment by famish99** [comment]
It will not time out because "now" is not being reread.

**Comment by famish99** [comment]
You could avoid the variable altogether to continue to use the continue, I
can make the change later, just didn't occur to me at the time

**Comment by hgrecco** [comment]
You are right, `now = ...` ended up in the wrong place. But I don't like the idea of flowing through the whole `while`. I think the right way would be to remove that variable and just do `time.time() - start` in the while condition.

Another question: You also added a test with `unexpected read`. There is no such thing as that error. reading when there is nothing to read yields a timeout.

**Comment by famish99** [comment]
Yeah it should expect an exception. It's just what I call the test to know
where it failed.

**Comment by famish99** [comment]
I will update the fix when I get to work, just want to make sure it passes
all my tests before checking it in.

**Comment by hgrecco** [comment]
Great!

**Comment by famish99** [comment]
Regarding the "unexpected read" test, I'd be preferred if it was left in but maybe renamed to "Read empty buffer" because my internal unit tests require the behavior.

Perhaps somewhere in the resource initialization, the timeout can be shorted to improve test time, but otherwise I'd rather keep the test in to ensure it won't break again in the future.

**Comment by hgrecco** [comment]
Sorry if I was unclear. It is fine to keep the test and is also fine that we raise a `VisaIOError(constants.VI_ERROR_TMO)`. What I do not want is to diverge from pyvisa.

**Comment by famish99** [comment]
Yeah, I think the test is consistent with pyvisa, but the naming sense is probably off because I just copied it from my internal unit tests.

**Comment by famish99** [comment]
Do you want to merge this pull request before I add another bugfix or should I combine it with this pull request?

**Comment by hgrecco** [comment]
I will merge them on friday. Thanks!

**Comment by famish99** [comment]
Is this even merge-able anymore?

**Comment by famish99** [comment]
This should be a pretty minor pull request.

**Pull request merged**
